[package]
name = "hlc_log_enrich"
version = "0.1.0"
authors = ["Steve Smith <steve.smith@batsnbat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
flate2 = "1.0"
hybrid-clocks = "0.5"