# Build component.

name: Build HLC Log Enricher

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Confirm source code
      run: ls -lash .
    - name: Confirm more source
      run: ls -lash ../
    - name: Build HLC Log Enrich
      run: docker build -t hlc_log_enrich .
    - name: Push to packages.
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: phaynes/hlc_log_enrich/hlc_log_enrich
        tag_with_ref: true
